library(gamlssPosthoc)
library(gamlss)
library(gamlss.dist)
set.seed(150)
d <- data.frame(dose=rep(seq(0,100,length.out=10),each=8))
d$y <- rGA(nrow(d),mu=exp(1+.015*d$dose-.00006*d$dose^2),sigma=exp(log(.2)+.002*d$dose))
fit <- gamlss(y~dose+I(dose^2),sigma.formula=~dose,family=GA,data=d,trace=FALSE)
plot_gamlss_parameters(fit,"dose",parameters=c("mu","sigma"),data=d)
plot_gamlss_estimand(fit,"dose",estimand="mean",data=d)
