library(gamlssPosthoc)
library(gamlss)
library(gamlss.dist)
set.seed(160)
d <- data.frame(trt=factor(rep(c("A","B"),each=50)))
d$y <- rGA(100,mu=ifelse(d$trt=="A",2,3),sigma=.3)
fit <- gamlss(y~trt,family=GA,data=d,trace=FALSE)
plot_gamlss_distribution(fit,"trt",type="density",data=d)
plot_gamlss_quantiles(fit,"trt",probs=c(.1,.5,.9),style="lines",data=d)
