library(gamlssPosthoc)
library(gamlss)
library(gamlss.dist)
set.seed(170)
d <- expand.grid(dose=seq(0,120,length.out=12),salinity=seq(0,3,length.out=5),rep=1:3)
mu <- exp(1+.018*d$dose-.00008*d$dose^2-.12*d$salinity)
d$y <- rGA(nrow(d),mu=mu,sigma=.22)
fit <- gamlss(y~dose+I(dose^2)+salinity,family=GA,data=d,trace=FALSE)
plot_gamlss_derivative(fit,"dose",order=1,data=d)
plot_gamlss_optimum(fit,"dose",data=d)
plot_gamlss_surface(fit,"dose","salinity",data=d)
