library(gamlssPosthoc)
library(gamlss)
library(gamlss.dist)
set.seed(180)
d <- data.frame(x=runif(120,0,2)); d$y <- rGA(120,mu=exp(.5+.4*d$x),sigma=.25)
m1 <- gamlss(y~x,family=GA,data=d,trace=FALSE)
m2 <- gamlss(y~pb(x),family=GA,data=d,trace=FALSE)
plot_gamlss_diagnostics(m1,"qq",data=d)
plot_gamlss_compare(linear=m1,smooth=m2,type="criteria")
